-- CREATE DATABASE OFFICE AND INSERT EMPLOYEE DATA
CREATE   DATABASE  IF NOT EXISTS office;

CREATE TABLE employee
(
EMPID INT PRIMARY KEY,
FirstName VARCHAR(90),
LastName VARCHAR(80),
Department VARCHAR(90),
Salary DECIMAL(10 ,2),
HireDate DATE
);


